[package]
name = "lt-ui"
version.workspace = true
edition.workspace = true

[dependencies]
lt-proto = { workspace = true }
lt-i18n = { workspace = true }
egui = { workspace = true }
egui-winit = { workspace = true }
egui-wgpu = { workspace = true }
winit = { workspace = true }
raw-window-handle = "0.6"
tray-icon = { workspace = true }
muda = { workspace = true }
rfd = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
pollster = { workspace = true }
tracing = { workspace = true }
parking_lot = { workspace = true }
sysinfo = { workspace = true }

[target."cfg(windows)".dependencies]
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging", # 穿透轮询（GetCursorPos/EXSTYLE）
    "Win32_Graphics_Gdi",
] }
